name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  design_system_lints:
    path: ../
  flutter:
    sdk: flutter
  path: ^1.8.0
  reflectable_flutter_analyzer:
    path: ../../../

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
