name: reflectable_analyzer
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  analyzer: ^4.7.0
  path: ^1.8.0
  reflectable: ^3.0.10
  source_gen: ^1.2.6
  build: ^2.3.1
  yaml: ^3.1.1
  source_span: ^1.8.2

dev_dependencies:
  build_runner: ^2.3.0
  lints: ^2.0.0
  test: ^1.16.0
